// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HistoryLevel5Js from "./HistoryLevel5.js";

let pageTitle = HistoryLevel5Js.pageTitle;

let pageHtmlUrl = HistoryLevel5Js.pageHtmlUrl;

function fetchSections(prim) {
  return HistoryLevel5Js.fetchSections();
}

export {
  pageTitle,
  pageHtmlUrl,
  fetchSections,
}
/* pageTitle Not a pure module */
