// Generated by ReScript, PLEASE EDIT WITH CARE

import * as VitalLevel5Js from "./VitalLevel5.js";

function fetchDivisions(prim) {
  return VitalLevel5Js.fetchDivisions();
}

export {
  fetchDivisions,
}
/* ./VitalLevel5.js Not a pure module */
