// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as HistoryLevel5 from "./wiki/HistoryLevel5.res.mjs";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let match = React.useState(() => {});
  let setSections = match[1];
  let sections = match[0];
  let match$1 = React.useState(() => {});
  let setError = match$1[1];
  let error = match$1[0];
  React.useEffect(() => {
    Stdlib_Promise.$$catch(HistoryLevel5.fetchSections().then(sections => {
      setSections(param => sections);
      return Promise.resolve();
    }), param => {
      setError(param => "Failed to load the History page.");
      return Promise.resolve();
    });
  }, []);
  let renderLink = link => {
    let href = "https://en.wikipedia.org" + link.href;
    return JsxRuntime.jsx("li", {
      children: JsxRuntime.jsx("a", {
        children: link.title,
        className: "text-sky-700 hover:text-sky-900 underline decoration-sky-300",
        href: href,
        rel: "noreferrer",
        target: "_blank"
      }),
      className: "my-1"
    }, link.href);
  };
  let renderSection = section => JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: section.title,
        className: "text-lg font-semibold text-stone-800"
      }),
      section.items.length !== 0 ? JsxRuntime.jsx("ul", {
          children: Belt_Array.map(section.items, renderLink),
          className: "ml-4 mt-2 list-disc text-sm text-stone-700"
        }) : null,
      section.children.length !== 0 ? JsxRuntime.jsx("div", {
          children: Belt_Array.map(section.children, renderSection),
          className: "ml-4 mt-3 border-l border-stone-200 pl-4"
        }) : null
    ],
    className: "my-4"
  });
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("p", {
            children: "Wikipedia Vital Articles",
            className: "text-sm uppercase tracking-widest text-stone-500"
          }),
          JsxRuntime.jsx("h1", {
            children: "Level 5 • History",
            className: "mt-2 text-4xl font-semibold text-stone-900"
          }),
          JsxRuntime.jsx("p", {
            children: "Browse and expand sections from the Vital Articles list.",
            className: "mt-2 text-stone-600"
          })
        ],
        className: "mb-8"
      }),
      error !== undefined ? JsxRuntime.jsx("div", {
          children: error,
          className: "rounded border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"
        }) : (
          sections !== undefined ? JsxRuntime.jsx("div", {
              children: Belt_Array.map(sections, renderSection),
              className: "rounded-2xl border border-stone-200 bg-white px-6 py-4 shadow-sm"
            }) : JsxRuntime.jsx("div", {
              children: "Loading sections…",
              className: "text-sm text-stone-500"
            })
        )
    ],
    className: "mx-auto max-w-5xl px-6 py-10"
  });
}

let make = App;

export {
  make,
}
/* react Not a pure module */
