// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_SetInt from "@rescript/runtime/lib/es6/Belt_SetInt.js";
import * as HistoryLevel5 from "./wiki/HistoryLevel5.res.mjs";
import * as Belt_SetString from "@rescript/runtime/lib/es6/Belt_SetString.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let levelMatchesSelection = (selectedLevels, levelOpt) => {
    if (levelOpt !== undefined) {
      return Belt_SetInt.has(selectedLevels, levelOpt);
    } else {
      return false;
    }
  };
  let match = React.useState(() => {});
  let setSections = match[1];
  let sections = match[0];
  let match$1 = React.useState(() => {});
  let setError = match$1[1];
  let error = match$1[0];
  let match$2 = React.useState(() => "");
  let setFilterText = match$2[1];
  let filterText = match$2[0];
  let match$3 = React.useState(() => {});
  let setExpanded = match$3[1];
  let expanded = match$3[0];
  let match$4 = React.useState(() => {});
  let setExpandedItems = match$4[1];
  let expandedItems = match$4[0];
  let match$5 = React.useState(() => Belt_SetInt.fromArray([
    1,
    2,
    3,
    4,
    5
  ]));
  let setSelectedLevels = match$5[1];
  let selectedLevels = match$5[0];
  console.log(sections);
  let collectKeys = (sections, prefix, acc) => Belt_Array.reduce(sections, acc, (acc, section) => {
    let key = prefix + "/" + section.title;
    let nextAcc = Belt_SetString.add(acc, key);
    return collectKeys(section.children, key, nextAcc);
  });
  let collectItemKeys = (items, prefix, acc) => Belt_Array.reduce(items, acc, (acc, item) => {
    let key = prefix + "/item/" + item.title;
    let nextAcc = Belt_SetString.add(acc, key);
    return collectItemKeys(item.children, key, nextAcc);
  });
  let collectAllItemKeys = (sections, prefix, acc) => Belt_Array.reduce(sections, acc, (acc, section) => {
    let nextAcc = collectItemKeys(section.items, prefix + "/" + section.title, acc);
    return collectAllItemKeys(section.children, prefix + "/" + section.title, nextAcc);
  });
  React.useEffect(() => {
    Stdlib_Promise.$$catch(HistoryLevel5.fetchSections().then(sections => {
      setSections(param => sections);
      setExpanded(param => collectKeys(sections, "root", undefined));
      setExpandedItems(param => collectAllItemKeys(sections, "root", undefined));
      return Promise.resolve();
    }), param => {
      setError(param => "Failed to load the History page.");
      return Promise.resolve();
    });
  }, []);
  let renderLink = (link, keyPrefix) => {
    let hasHref = link.href !== "";
    let href = "https://en.wikipedia.org" + link.href;
    let key = keyPrefix + "/item/" + link.title;
    let isOpen = Belt_SetString.has(expandedItems, key);
    let level = link.level;
    return JsxRuntime.jsxs("li", {
      children: [
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsxs("span", {
              children: [
                hasHref ? JsxRuntime.jsx("a", {
                    children: link.title,
                    className: "text-sky-700 hover:text-sky-900 underline decoration-sky-300",
                    href: href,
                    rel: "noreferrer",
                    target: "_blank"
                  }) : JsxRuntime.jsx("span", {
                    children: link.title,
                    className: "text-stone-700"
                  }),
                level !== undefined && level !== 5 ? JsxRuntime.jsx("span", {
                    children: level.toString(),
                    className: "ml-1"
                  }) : null
              ]
            }),
            link.children.length !== 0 ? JsxRuntime.jsx("button", {
                children: isOpen ? "−" : "+",
                className: "rounded border-stone-200 px-2 py-1 text-[10px] font-semibold text-stone-600 hover:border-stone-300",
                onClick: param => setExpandedItems(prev => {
                  if (Belt_SetString.has(prev, key)) {
                    return Belt_SetString.remove(prev, key);
                  } else {
                    return Belt_SetString.add(prev, key);
                  }
                })
              }) : null
          ],
          className: "flex items-center gap-2"
        }),
        link.children.length !== 0 && isOpen ? JsxRuntime.jsx("ul", {
            children: Belt_Array.map(link.children, child => renderLink(child, key)),
            className: "ml-5 mt-2 list-disc text-sm text-stone-600"
          }) : null
      ],
      className: "my-1"
    }, link.title);
  };
  let query = filterText.toLowerCase();
  let filterSection = section => {
    let titleMatch = section.title.toLowerCase().includes(query);
    let filterItem = item => {
      let levelMatch = levelMatchesSelection(selectedLevels, item.level);
      let itemMatch = item.title.toLowerCase().includes(query);
      let children = Belt_Array.keepMap(item.children, filterItem);
      if (levelMatch && (query === "" || itemMatch) || children.length !== 0) {
        return {
          title: item.title,
          href: item.href,
          level: item.level,
          children: children
        };
      }
    };
    let items = Belt_Array.keepMap(section.items, filterItem);
    let children = Belt_Array.keepMap(section.children, filterSection);
    if (query === "") {
      if (items.length !== 0 || children.length !== 0) {
        return {
          title: section.title,
          level: section.level,
          items: items,
          children: children
        };
      } else {
        return;
      }
    } else if (titleMatch || items.length !== 0 || children.length !== 0) {
      return {
        title: section.title,
        level: section.level,
        items: items,
        children: children
      };
    } else {
      return;
    }
  };
  let expandAll = () => {
    if (sections !== undefined) {
      setExpanded(param => collectKeys(sections, "root", undefined));
      return setExpandedItems(param => collectAllItemKeys(sections, "root", undefined));
    }
  };
  let renderSection = (section, keyPrefix) => {
    let key = keyPrefix + "/" + section.title;
    let isOpen = Belt_SetString.has(expanded, key);
    return JsxRuntime.jsxs("div", {
      children: [
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsx("span", {
              children: section.title
            }),
            JsxRuntime.jsx("button", {
              children: isOpen ? "−" : "+",
              className: "rounded border-stone-200 px-2 py-1 text-xs font-semibold text-stone-600 hover:border-stone-300",
              onClick: param => setExpanded(prev => {
                if (Belt_SetString.has(prev, key)) {
                  return Belt_SetString.remove(prev, key);
                } else {
                  return Belt_SetString.add(prev, key);
                }
              })
            })
          ],
          className: "flex items-center gap-2 font-semibold text-stone-800"
        }),
        isOpen ? JsxRuntime.jsxs("div", {
            children: [
              section.items.length !== 0 ? JsxRuntime.jsx("ul", {
                  children: Belt_Array.map(section.items, item => renderLink(item, key)),
                  className: "ml-8 list-disc text-sm text-stone-700"
                }) : null,
              section.children.length !== 0 ? JsxRuntime.jsx("div", {
                  children: Belt_Array.map(section.children, child => renderSection(child, key)),
                  className: " border-stone-200"
                }) : null
            ]
          }) : null
      ],
      className: "ml-4"
    });
  };
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("p", {
            children: "Wikipedia Vital Articles",
            className: "text-sm uppercase tracking-widest text-stone-500"
          }),
          JsxRuntime.jsx("h1", {
            children: "Level 5 • History",
            className: "mt-2 text-4xl font-semibold text-stone-900"
          }),
          JsxRuntime.jsx("p", {
            children: "Browse and expand sections from the Vital Articles list.",
            className: "mt-2 text-stone-600"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("input", {
                className: "w-full rounded-xl border border-stone-200 bg-white px-4 py-3 text-sm text-stone-700 shadow-sm focus:border-sky-300 focus:outline-none",
                placeholder: "Filter sections or articles",
                value: filterText,
                onChange: event => setFilterText(param => event.target.value)
              }),
              JsxRuntime.jsxs("div", {
                children: [
                  Belt_Array.map([
                    1,
                    2,
                    3,
                    4,
                    5
                  ], level => {
                    let isSelected = Belt_SetInt.has(selectedLevels, level);
                    return JsxRuntime.jsx("button", {
                      children: "Level " + level.toString(),
                      className: "rounded-lg border px-3 py-2 text-xs font-semibold uppercase tracking-wider " + (
                        isSelected ? "border-sky-300 bg-sky-50 text-sky-800" : "border-stone-200 bg-white text-stone-600 hover:border-stone-300"
                      ),
                      onClick: param => setSelectedLevels(prev => {
                        if (Belt_SetInt.has(prev, level)) {
                          return Belt_SetInt.remove(prev, level);
                        } else {
                          return Belt_SetInt.add(prev, level);
                        }
                      })
                    }, level.toString());
                  }),
                  JsxRuntime.jsx("button", {
                    children: "Expand all",
                    className: "rounded-lg border border-stone-200 bg-white px-3 py-2 text-xs font-semibold uppercase tracking-wider text-stone-600 hover:border-stone-300",
                    onClick: param => expandAll()
                  }),
                  JsxRuntime.jsx("button", {
                    children: "Collapse all",
                    className: "rounded-lg border border-stone-200 bg-white px-3 py-2 text-xs font-semibold uppercase tracking-wider text-stone-600 hover:border-stone-300",
                    onClick: param => {
                      setExpanded(param => {});
                      setExpandedItems(param => {});
                    }
                  })
                ],
                className: "flex flex-wrap gap-2"
              })
            ],
            className: "mt-4 flex flex-col gap-3 md:flex-row md:items-center"
          })
        ],
        className: "mb-8"
      }),
      error !== undefined ? JsxRuntime.jsx("div", {
          children: error,
          className: "rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700"
        }) : (
          sections !== undefined ? JsxRuntime.jsx("div", {
              children: Belt_Array.map(Belt_Array.keepMap(sections, filterSection), section => renderSection(section, "root")),
              className: "  bg-white"
            }) : JsxRuntime.jsx("div", {
              children: "Loading sections…",
              className: "text-sm text-stone-500"
            })
        )
    ],
    className: "mx-auto max-w-5xl p-6"
  });
}

let make = App;

export {
  make,
}
/* react Not a pure module */
